site:
    title: "Paparadise"
    subtitle: "不要看轻前端职业，更不要看轻自己"
    limit: 10
    theme: theme
    lang: zh
    url: "https://github.com/Paparadise/Paparadise.github.io.git"
    comment: Paparadise
    logo: "-/images/avatar1.jpg"
    # link: "{category}/{year}/{month}/{day}/{title}.html"
    # root: "/blog"

authors:
    me:
        name: "Paparadise"
        intro: "不要看轻前端职业，更不要看轻自己"
        avatar: "-/images/avatar1.jpg"

build:
    # output: "public"
    port: 8000
    # Copied files to public folder when build
    copy:
        - "source/images"
    # Excuted command when use 'ink publish'
    publish: |
        git add . -A
        git commit -m "update"
        git push origin
